// Code generated by Slice Machine. DO NOT EDIT.

import Contextindex from './Contextindex/index.svelte'
import RelatedPosts from './RelatedPosts/index.svelte'
import RecentPosts from './RecentPosts/index.svelte'
import RichText from './RichText/index.svelte'
import Testimonials from './Testimonials/index.svelte'

export const components = {
	contextindex: Contextindex,
	related_posts: RelatedPosts,
	recent_posts: RecentPosts,
	rich_text: RichText,
	testimonials: Testimonials,
}
