// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type BlogpostDocumentDataSlicesSlice = RichTextSlice

/**
 * Content for blogpost documents
 */
interface BlogpostDocumentData {
	/**
	 * date field in *blogpost*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blogpost.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	date: prismic.DateField

	/**
	 * title field in *blogpost*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blogpost.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * image field in *blogpost*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blogpost.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>

	/**
	 * Slice Zone field in *blogpost*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blogpost.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<BlogpostDocumentDataSlicesSlice> /**
	 * Meta Title field in *blogpost*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: blogpost.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *blogpost*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: blogpost.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *blogpost*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blogpost.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * blogpost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<BlogpostDocumentData>, 'blogpost', Lang>

type PageDocumentDataSlicesSlice =
	| RecentPostsSlice
	| TestimonialsSlice
	| ContextindexSlice
	| RichTextSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>

/**
 * Item in *Settings → navigation*
 */
export interface SettingsDocumentDataNavigationItem {
	/**
	 * link field in *Settings → navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField

	/**
	 * label field in *Settings → navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * website url field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.website_url
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	website_url: prismic.KeyTextField

	/**
	 * site title field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.site_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	site_title: prismic.KeyTextField

	/**
	 * meta description field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * og image field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.og_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>

	/**
	 * navigation field in *Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<Simplify<SettingsDocumentData>, 'settings', Lang>

type ShowcaseDocumentDataSlicesSlice = never

/**
 * Content for showcase documents
 */
interface ShowcaseDocumentData {
	/**
	 * Slice Zone field in *showcase*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ShowcaseDocumentDataSlicesSlice> /**
	 * Meta Title field in *showcase*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: showcase.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *showcase*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: showcase.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *showcase*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * showcase document from Prismic
 *
 * - **API ID**: `showcase`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ShowcaseDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<ShowcaseDocumentData>, 'showcase', Lang>

type TestimonialDocumentDataSlicesSlice = never

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
	/**
	 * person field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonial.person
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	person: prismic.KeyTextField

	/**
	 * title field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonial.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * avatar field in *Testimonial*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonial.avatar
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	avatar: prismic.ImageField<never>

	/**
	 * text field in *Testimonial*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonial.text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField

	/**
	 * Slice Zone field in *Testimonial*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonial.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<TestimonialDocumentDataSlicesSlice> /**
	 * Meta Title field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: testimonial.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: testimonial.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *Testimonial*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonial.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<TestimonialDocumentData>, 'testimonial', Lang>

export type AllDocumentTypes =
	| BlogpostDocument
	| PageDocument
	| SettingsDocument
	| ShowcaseDocument
	| TestimonialDocument

/**
 * Primary content in *Contextindex → Default → Primary*
 */
export interface ContextindexSliceDefaultPrimary {
	/**
	 * heading field in *Contextindex → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contextindex.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField

	/**
	 * context type field in *Contextindex → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contextindex.default.primary.context_type
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	context_type: prismic.SelectField<'Blog' | 'Showcase'>

	/**
	 * description field in *Contextindex → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contextindex.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField

	/**
	 * more label field in *Contextindex → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contextindex.default.primary.more_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	more_label: prismic.KeyTextField

	/**
	 * fallback_img field in *Contextindex → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contextindex.default.primary.fallback_img
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	fallback_img: prismic.ImageField<never>
}

/**
 * Default variation for Contextindex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContextindexSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ContextindexSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *Contextindex*
 */
type ContextindexSliceVariation = ContextindexSliceDefault

/**
 * Contextindex Shared Slice
 *
 * - **API ID**: `contextindex`
 * - **Description**: Contextindex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContextindexSlice = prismic.SharedSlice<
	'contextindex',
	ContextindexSliceVariation
>

/**
 * Primary content in *RecentPosts → Default → Primary*
 */
export interface RecentPostsSliceDefaultPrimary {
	/**
	 * heading field in *RecentPosts → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent_posts.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField

	/**
	 * description field in *RecentPosts → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent_posts.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField

	/**
	 * more label field in *RecentPosts → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent_posts.default.primary.more_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	more_label: prismic.KeyTextField

	/**
	 * fallback_img field in *RecentPosts → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent_posts.default.primary.fallback_img
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	fallback_img: prismic.ImageField<never>

	/**
	 * amount field in *RecentPosts → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 3
	 * - **API ID Path**: recent_posts.default.primary.amount
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	amount: prismic.SelectField<'3' | '5', 'filled'>
}

/**
 * Default variation for RecentPosts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecentPostsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RecentPostsSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *RecentPosts*
 */
type RecentPostsSliceVariation = RecentPostsSliceDefault

/**
 * RecentPosts Shared Slice
 *
 * - **API ID**: `recent_posts`
 * - **Description**: RecentPosts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecentPostsSlice = prismic.SharedSlice<
	'recent_posts',
	RecentPostsSliceVariation
>

/**
 * Primary content in *RelatedPosts → Default → Primary*
 */
export interface RelatedPostsSliceDefaultPrimary {
	/**
	 * heading field in *RelatedPosts → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: related_posts.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField
}

/**
 * Default variation for RelatedPosts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RelatedPostsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RelatedPostsSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *RelatedPosts*
 */
type RelatedPostsSliceVariation = RelatedPostsSliceDefault

/**
 * RelatedPosts Shared Slice
 *
 * - **API ID**: `related_posts`
 * - **Description**: RelatedPosts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RelatedPostsSlice = prismic.SharedSlice<
	'related_posts',
	RelatedPostsSliceVariation
>

/**
 * Item in *RichText → Default → Primary → button*
 */
export interface RichTextSliceDefaultPrimaryButtonItem {
	/**
	 * label field in *RichText → Default → Primary → button*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.default.primary.button[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField

	/**
	 * link field in *RichText → Default → Primary → button*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.default.primary.button[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField
}

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField

	/**
	 * link field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField

	/**
	 * label field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField

	/**
	 * button field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.default.primary.button[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	button: prismic.GroupField<Simplify<RichTextSliceDefaultPrimaryButtonItem>>
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
	/**
	 * heading field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
	/**
	 * testimonial field in *Testimonials → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.items[].testimonial
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	testimonial: prismic.ContentRelationshipField<'testimonial'>
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TestimonialsSliceDefaultPrimary>,
	Simplify<TestimonialsSliceDefaultItem>
>

/**
 * Primary content in *Testimonials → zPopout → Primary*
 */
export interface TestimonialsSliceZPopoutPrimary {
	/**
	 * heading field in *Testimonials → zPopout → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.zPopout.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceZPopoutItem {
	/**
	 * testimonial field in *Testimonials → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.items[].testimonial
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	testimonial: prismic.ContentRelationshipField<'testimonial'>
}

/**
 * zPopout variation for Testimonials Slice
 *
 * - **API ID**: `zPopout`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceZPopout = prismic.SharedSliceVariation<
	'zPopout',
	Simplify<TestimonialsSliceZPopoutPrimary>,
	Simplify<TestimonialsSliceZPopoutItem>
>

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault | TestimonialsSliceZPopout

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
	'testimonials',
	TestimonialsSliceVariation
>

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig,
		): prismic.WriteClient<AllDocumentTypes>
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>
	}

	namespace Content {
		export type {
			BlogpostDocument,
			BlogpostDocumentData,
			BlogpostDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataNavigationItem,
			ShowcaseDocument,
			ShowcaseDocumentData,
			ShowcaseDocumentDataSlicesSlice,
			TestimonialDocument,
			TestimonialDocumentData,
			TestimonialDocumentDataSlicesSlice,
			AllDocumentTypes,
			ContextindexSlice,
			ContextindexSliceDefaultPrimary,
			ContextindexSliceVariation,
			ContextindexSliceDefault,
			RecentPostsSlice,
			RecentPostsSliceDefaultPrimary,
			RecentPostsSliceVariation,
			RecentPostsSliceDefault,
			RelatedPostsSlice,
			RelatedPostsSliceDefaultPrimary,
			RelatedPostsSliceVariation,
			RelatedPostsSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimaryButtonItem,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			TestimonialsSlice,
			TestimonialsSliceDefaultPrimary,
			TestimonialsSliceDefaultItem,
			TestimonialsSliceZPopoutPrimary,
			TestimonialsSliceZPopoutItem,
			TestimonialsSliceVariation,
			TestimonialsSliceDefault,
			TestimonialsSliceZPopout,
		}
	}
}
